export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE";

export const GET_STUDENT_APPLICATION_REQUEST = "GET_STUDENT_APPLICATION_REQUEST";
export const GET_STUDENT_APPLICATION_SUCCESS = "GET_STUDENT_APPLICATION_SUCCESS";
export const GET_STUDENT_APPLICATION_FAILURE = "GET_STUDENT_APPLICATION_FAILURE";

export const GET_STUDENT_APPLICATIONS_REQUEST = "GET_STUDENT_APPLICATIONS_REQUEST";
export const GET_STUDENT_APPLICATIONS_SUCCESS = "GET_STUDENT_APPLICATIONS_SUCCESS";
export const GET_STUDENT_APPLICATIONS_FAILURE = "GET_STUDENT_APPLICATIONS_FAILURE";