export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAILURE = "GET_STUDENT_FAILURE";

export const GET_STUDENT_APPLICATION_REQUEST = "GET_STUDENT_APPLICATION_REQUEST";
export const GET_STUDENT_APPLICATION_SUCCESS = "GET_STUDENT_APPLICATION_SUCCESS";
export const GET_STUDENT_APPLICATION_FAILURE = "GET_STUDENT_APPLICATION_FAILURE";

export const GET_STUDENT_APPLICATIONS_REQUEST = "GET_STUDENT_APPLICATIONS_REQUEST";
export const GET_STUDENT_APPLICATIONS_SUCCESS = "GET_STUDENT_APPLICATIONS_SUCCESS";
export const GET_STUDENT_APPLICATIONS_FAILURE = "GET_STUDENT_APPLICATIONS_FAILURE";

export const GET_PERSONAL_INFORMATION_SUCCESS = "GET_PERSONAL_INFORMATION_SUCCESS";
export const GET_PERSONAL_INFORMATION_REQUEST = "GET_PERSONAL_INFORMATION_REQUEST";
export const GET_PERSONAL_INFORMATION_FAILURE = "GET_PERSONAL_INFORMATION_FAILURE";

export const GET_ENROLLMENT_PLAN_REQUEST = "GET_ENROLLMENT_PLAN_REQUEST";
export const GET_ENROLLMENT_PLAN_SUCCESS = "GET_ENROLLMENT_PLAN_SUCCESS";
export const GET_ENROLLMENT_PLAN_FAILURE = "GET_ENROLLMENT_PLAN_FAILURE";

export const GET_ACADEMIC_HISTORY_REQUEST = "GET_ACADEMIC_HISTORY_REQUEST";
export const GET_ACADEMIC_HISTORY_SUCCESS = "GET_ACADEMIC_HISTORY_SUCCESS";
export const GET_ACADEMIC_HISTORY_FAILURE = "GET_ACADEMIC_HISTORY_FAILURE";

export const CREATE_STUDENT_APPLICATION_REQUEST = "CREATE_STUDENT_APPLICATION_REQUEST";
export const CREATE_STUDENT_APPLICATION_SUCCESS = "CREATE_STUDENT_APPLICATION_SUCCESS";
export const CREATE_STUDENT_APPLICATION_FAILURE = "CREATE_STUDENT_APPLICATION_FAILURE";

export const CREATE_PERSONAL_INFORMATION_REQUEST = "CREATE_PERSONAL_INFORMATION_REQUEST";
export const CREATE_PERSONAL_INFORMATION_SUCCESS = "CREATE_PERSONAL_INFORMATION_SUCCESS";
export const CREATE_PERSONAL_INFORMATION_FAILURE = "CREATE_PERSONAL_INFORMATION_FAILURE";

export const CREATE_ENROLLMENT_PLAN_REQUEST = "CREATE_ENROLLMENT_PLAN_REQUEST";
export const CREATE_ENROLLMENT_PLAN_SUCCESS = "CREATE_ENROLLMENT_PLAN_SUCCESS";
export const CREATE_ENROLLMENT_PLAN_FAILURE = "CREATE_ENROLLMENT_PLAN_FAILURE";

export const CREATE_ACADEMIC_HISTORY_REQUEST = "CREATE_ACADEMIC_HISTORY_REQUEST";
export const CREATE_ACADEMIC_HISTORY_SUCCESS = "CREATE_ACADEMIC_HISTORY_SUCCESS";
export const CREATE_ACADEMIC_HISTORY_FAILURE = "CREATE_ACADEMIC_HISTORY_FAILURE";